// Render the website's survey section from tools/survey-content.mjs into index.html, between the survey markers.
//
//   node tools/render-survey.mjs          # rewrite the section in index.html
//   node tools/render-survey.mjs --check  # fail if index.html is out of date
//
// The README (tools/render-readme.mjs) draws on the same content, so the two cannot drift apart.
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { REPO_URL, ROOT } from "./public-files.mjs";
import {
  ABOUT,
  CLOSING,
  CONDITIONS,
  CONDITIONS_NOTE,
  EVIDENCE,
  FIGURES,
  PROBLEMS,
  PROGRAMS,
  QUESTIONS,
  RECURSION,
  SURVEY,
  TEASER_ALT,
  USES,
  surveyBibtex,
} from "./survey-content.mjs";

export const START = "<!-- survey:start (generated by tools/render-survey.mjs; edit tools/survey-content.mjs) -->";
export const END = "<!-- survey:end -->";
const FIGURE_SIZE = { 1: [1600, 623], 2: [1600, 823], 3: [1600, 865], 6: [1600, 790] };

function html(value) {
  return String(value).replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character],
  );
}

// The survey text uses *emphasis* from Markdown; render it as <em>.
function inline(value) {
  return html(value).replace(/\*([^*]+)\*/g, "<em>$1</em>");
}

function figure(number) {
  const [title, caption] = FIGURES[number];
  const [width, height] = FIGURE_SIZE[number];
  return [
    '<figure class="survey-figure">',
    `  <img src="assets/readme/figures/figure-${number}.png" width="${width}" height="${height}" loading="lazy" decoding="async" alt="Figure ${number}. ${html(title)}" />`,
    `  <figcaption><strong>Figure ${number}. ${html(title)}</strong> ${html(caption)}</figcaption>`,
    "</figure>",
  ];
}

export function renderSurveySection() {
  const authors = SURVEY.authors
    .map(([name, affiliations]) => `<span>${html(name)}<sup>${affiliations.join(",")}</sup></span>`)
    .join("");
  const lines = [
    '<section id="survey" class="survey-section" aria-labelledby="survey-title">',
    '  <div class="container">',
    '    <header class="survey-header">',
    '      <p class="eyebrow section-eyebrow">The survey</p>',
    `      <h2 id="survey-title">From Physical Experience to <span>Recursive Self&#8209;Improvement</span><span class="heading-dot">.</span></h2>`,
    `      <p class="survey-subtitle">${html(SURVEY.subtitle)}</p>`,
    `      <p class="survey-authors">${authors}</p>`,
    `      <p class="survey-affiliations">${SURVEY.affiliations.map((name, i) => `<span><sup>${i + 1}</sup>${html(name)}</span>`).join("")}</p>`,
    '      <p class="survey-note"><span class="status-dot"></span>The manuscript is not yet public. This summary is shared with the authors&#39; approval.</p>',
    "    </header>",
    '    <figure class="survey-teaser">',
    `      <img src="assets/teaser.webp" width="1774" height="887" decoding="async" alt="${html(TEASER_ALT)}" />`,
    "    </figure>",
    '    <div class="survey-intro">',
    '      <div class="survey-abstract">',
    ...ABOUT.map((paragraph) => `        <p>${inline(paragraph)}</p>`),
    "      </div>",
    '      <aside class="condition-panel" aria-labelledby="survey-conditions-title">',
    '        <h3 id="survey-conditions-title">Four recurring conditions</h3>',
    '        <ol class="condition-list">',
    ...CONDITIONS.map(([name, text]) => `          <li><strong>${html(name)}</strong><span>${html(text[0].toUpperCase() + text.slice(1))}</span></li>`),
    "        </ol>",
    `        <p>${html(CONDITIONS_NOTE)}</p>`,
    "      </aside>",
    "    </div>",
    ...figure(1).map((line) => `    ${line}`),
    '    <div class="survey-block">',
    '      <h3 id="survey-questions">Research questions</h3>',
    '      <ol class="question-grid">',
    ...QUESTIONS.map(([id, question, detail]) => `        <li><span class="question-id">${id}</span><strong>${html(question)}</strong><p>${html(detail)}</p></li>`),
    "      </ol>",
    "    </div>",
    '    <div class="survey-block">',
    '      <h3 id="survey-framework">The review at a glance</h3>',
    ...figure(2).map((line) => `      ${line}`),
    `      <p class="evidence-note"><strong>What current evidence shows.</strong> ${html(EVIDENCE)}</p>`,
    "    </div>",
    '    <div class="survey-block">',
    '      <h3 id="survey-uses">Four uses of acquired change</h3>',
    '      <div class="use-grid">',
  ];
  for (const [use, change, next, claim, chapter] of USES)
    lines.push(
      '        <article class="use-card">',
      `          <p class="use-chapter">${html(chapter)}</p>`,
      `          <h4>${html(use)}</h4>`,
      `          <dl><div><dt>Retained change</dt><dd>${html(change)}</dd></div><div><dt>Immediate use</dt><dd>${html(next)}</dd></div><div><dt>Principal claim</dt><dd>${html(claim)}</dd></div></dl>`,
      "        </article>",
    );
  lines.push(
    "      </div>",
    ...figure(3).map((line) => `      ${line}`),
    "    </div>",
    '    <div class="survey-block">',
    '      <h3 id="survey-recursion">Toward recursive self-improvement</h3>',
    ...figure(6).map((line) => `      ${line}`),
    '      <ul class="recursion-list">',
    ...RECURSION.map(([lead, text]) => `        <li><strong>${html(lead)}</strong> ${html(text)}</li>`),
    "      </ul>",
    "    </div>",
    '    <div class="survey-block">',
    '      <h3 id="survey-problems">Open problems</h3>',
    '      <div class="problem-grid">',
  );
  for (const [direction, serves, question, benchmark] of PROBLEMS)
    lines.push(
      '        <article class="problem-card">',
      `          <h4>${html(direction)}</h4>`,
      `          <p class="problem-tags">${serves.map((name) => `<span>${html(name)}</span>`).join("")}</p>`,
      `          <p class="problem-question">${html(question)}</p>`,
      `          <p class="problem-benchmark"><span>Starting benchmark</span>${html(benchmark)}</p>`,
      "        </article>",
    );
  lines.push(
    "      </div>",
    '      <h4 class="program-title">Three near-term programs</h4>',
    '      <ol class="program-list">',
    ...PROGRAMS.map((program) => `        <li>${html(program)}</li>`),
    "      </ol>",
    `      <blockquote class="survey-closing">${html(CLOSING)}</blockquote>`,
    "    </div>",
    '    <div class="survey-block survey-cite">',
    '      <h3 id="survey-citation">Cite the survey</h3>',
    `      <pre id="survey-bibtex"><code>${html(surveyBibtex(REPO_URL))}</code></pre>`,
    '      <button type="button" class="button button-outline" id="copy-bibtex">Copy BibTeX<img class="icon" src="assets/icons/copy.svg" alt="" width="16" height="16" /></button>',
    "    </div>",
    "  </div>",
    "</section>",
  );
  return lines.map((line) => (line ? `      ${line}` : line)).join("\n");
}

export function applySurveySection(page) {
  const start = page.indexOf(START);
  const end = page.indexOf(END);
  if (start < 0 || end < start) throw new Error("index.html is missing the survey markers");
  return `${page.slice(0, start + START.length)}\n${renderSurveySection()}\n      ${page.slice(end)}`;
}

if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  const file = path.join(ROOT, "index.html");
  const page = await readFile(file, "utf8");
  const output = applySurveySection(page);
  if (process.argv.includes("--check")) {
    if (output !== page) throw new Error("Survey section is out of date. Run npm run readme.");
    console.log("Survey section is synchronized.");
  } else {
    await writeFile(file, output);
    console.log("Survey section rendered into index.html.");
  }
}
