// Render the website's hero (the paper's title, authors and links over the night sky) and its survey section from
// tools/survey-content.mjs into index.html, between the survey markers.
//
//   node tools/render-survey.mjs          # rewrite the section in index.html
//   node tools/render-survey.mjs --check  # fail if index.html is out of date
//
// The README (tools/render-readme.mjs) draws on the same content, so the two cannot drift apart.
import { readFileSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { REPO_URL, ROOT } from "./public-files.mjs";
import {
  ABOUT,
  CLOSING,
  CONDITIONS,
  CONDITIONS_NOTE,
  EVIDENCE,
  FIGURES,
  PROBLEMS,
  PROGRAMS,
  QUESTIONS,
  RECURSION,
  SURVEY,
  TEASER_ALT,
  USES,
  surveyBibtex,
} from "./survey-content.mjs";

export const START = "<!-- survey:start (generated by tools/render-survey.mjs; edit tools/survey-content.mjs) -->";
export const END = "<!-- survey:end -->";

// Intrinsic size of a PNG or WebP, read from its header, so width/height attributes always match the file.
export function imageSize(file) {
  const b = readFileSync(path.join(ROOT, file));
  if (b.toString("ascii", 1, 4) === "PNG") return [b.readUInt32BE(16), b.readUInt32BE(20)];
  if (b.toString("ascii", 0, 4) === "RIFF" && b.toString("ascii", 8, 12) === "WEBP") {
    const chunk = b.toString("ascii", 12, 16);
    if (chunk === "VP8X") return [b.readUIntLE(24, 3) + 1, b.readUIntLE(27, 3) + 1];
    if (chunk === "VP8L") {
      const bits = b.readUInt32LE(21);
      return [(bits & 0x3fff) + 1, ((bits >> 14) & 0x3fff) + 1];
    }
    if (chunk === "VP8 ") return [b.readUInt16LE(26) & 0x3fff, b.readUInt16LE(28) & 0x3fff];
  }
  throw new Error(`Unsupported image: ${file}`);
}

function html(value) {
  return String(value).replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character],
  );
}

// The survey text uses *emphasis* from Markdown; render it as <em>.
function inline(value) {
  return html(value).replace(/\*([^*]+)\*/g, "<em>$1</em>");
}

function figure(number) {
  const [title, caption] = FIGURES[number];
  const [width, height] = imageSize(`assets/readme/figures/figure-${number}.png`);
  return [
    '<figure class="survey-figure">',
    `  <img src="assets/readme/figures/figure-${number}.png" width="${width}" height="${height}" loading="lazy" decoding="async" alt="Figure ${number}. ${html(title)}" />`,
    `  <figcaption><strong>Figure ${number}. ${html(title)}</strong> ${html(caption)}</figcaption>`,
    "</figure>",
  ];
}

const ICON = (d) =>
  `<svg viewBox="0 0 16 16" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${d}</svg>`;
const GITHUB_ICON =
  '<svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true"><path fill="currentColor" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/></svg>';

// The hero: the paper's title, authors and links over the night sky, with the teaser painting framed beside them.
export function renderHero() {
  const authors = SURVEY.authors
    .map(([name, affiliations]) => `<span>${html(name)}<sup>${affiliations.join(",")}</sup></span>`)
    .join("");
  const affiliations = SURVEY.affiliations.map((name, i) => `<span><sup>${i + 1}</sup>${html(name)}</span>`).join("");
  return [
    '<section id="top" class="hero" aria-labelledby="project-title" data-chapter="Title">',
    '  <canvas class="hero-sky" aria-hidden="true"></canvas>',
    '  <div class="hero-inner">',
    '    <div class="hero-copy">',
    '      <p class="hero-eyebrow"><span class="status-dot"></span>Physical AI + RSI · A survey &amp; reference library</p>',
    `      <h1 id="project-title">From Physical Experience to <span>Recursive Self&#8209;Improvement</span></h1>`,
    `      <p class="hero-subtitle">${html(SURVEY.subtitle)}</p>`,
    `      <p class="hero-authors">${authors}</p>`,
    `      <p class="hero-affiliations">${affiliations}</p>`,
    '      <div class="hero-actions">',
    `        <a href="#survey" class="button button-gold">Read the survey${ICON('<path d="M8 2.5v10M3.5 8.5 8 13l4.5-4.5"/>')}</a>`,
    `        <a href="#references" class="button button-glass">${ICON('<path d="M2.5 3.5h4l1.5 1.5v8l-1.5-1H2.5zM13.5 3.5h-4L8 5v8l1.5-1h4z"/>')}Reference library</a>`,
    `        <a href="#survey-citation" class="button button-glass">${ICON('<path d="M3.5 2.5h9v11l-4.5-3-4.5 3z"/>')}BibTeX</a>`,
    `        <a href="${REPO_URL}" class="button button-glass" target="_blank" rel="noopener noreferrer">${GITHUB_ICON}GitHub</a>`,
    "      </div>",
    '      <p class="hero-note">Paper coming soon · this page summarizes the manuscript with the authors&#39; approval</p>',
    "    </div>",
    '    <figure class="hero-art">',
    `      <img src="assets/teaser.webp" width="${imageSize("assets/teaser.webp")[0]}" height="${imageSize("assets/teaser.webp")[1]}" fetchpriority="high" alt="${html(TEASER_ALT)}" />`,
    "    </figure>",
    "  </div>",
    "</section>",
  ];
}

// The survey's own robot illustrations (assets/art, from the manuscript's figures), keyed by their figure role.
const CONDITION_ART = ["signal", "recipient", "shift", "continuation"];
const USE_ART = ["act", "practice", "reuse", "procedure"];

function art(name, className) {
  const [width, height] = imageSize(`assets/art/${name}.webp`);
  return `<img class="${className}" src="assets/art/${name}.webp" width="${width}" height="${height}" loading="lazy" decoding="async" alt="" />`;
}

// A numbered survey block: eyebrow with its number and the heading, a robot beside them, then the body lines.
function block(number, id, title, heading, robot, body, extraClass = "") {
  return [
    `<div class="survey-block${extraClass}" id="${id}" data-reveal data-chapter="${html(title)}">`,
    '  <div class="block-head">',
    "    <div>",
    `      <p class="block-eyebrow"><span>${String(number).padStart(2, "0")}</span>${html(title)}</p>`,
    `      <h3 class="block-title">${html(heading)}</h3>`,
    "    </div>",
    `    ${art(robot, "block-art")}`,
    "  </div>",
    ...body.map((line) => `  ${line}`),
    "</div>",
  ];
}

export function renderSurveySection() {
  const intro = [
    '<div class="survey-intro">',
    '  <div class="survey-abstract">',
    ...ABOUT.map((paragraph) => `    <p>${inline(paragraph)}</p>`),
    "  </div>",
    '  <aside class="condition-panel" aria-labelledby="survey-conditions-title">',
    '    <h3 id="survey-conditions-title">Four recurring conditions</h3>',
    '    <ol class="condition-list">',
    ...CONDITIONS.map(([name, text], i) => `      <li>${art(CONDITION_ART[i], "condition-art")}<div><strong>${html(name)}</strong><span>${html(text[0].toUpperCase() + text.slice(1))}</span></div></li>`),
    "    </ol>",
    `    <p>${html(CONDITIONS_NOTE)}</p>`,
    "  </aside>",
    "</div>",
    ...figure(1),
  ];
  const questions = [
    '<ol class="question-grid">',
    ...QUESTIONS.map(([id, question, detail]) => `  <li><span class="question-id">${id}</span><strong>${html(question)}</strong><p>${html(detail)}</p></li>`),
    "</ol>",
  ];
  const framework = [
    ...figure(2),
    `<p class="evidence-note"><strong>What current evidence shows.</strong> ${html(EVIDENCE)}</p>`,
  ];
  const uses = ['<div class="use-grid">'];
  for (const [i, [use, change, next, claim, chapter]] of USES.entries())
    uses.push(
      '  <article class="use-card">',
      `    ${art(USE_ART[i], "use-art")}`,
      `    <p class="use-chapter">${html(chapter)}</p>`,
      `    <h4>${html(use)}</h4>`,
      `    <dl><div><dt>Retained change</dt><dd>${html(change)}</dd></div><div><dt>Immediate use</dt><dd>${html(next)}</dd></div><div><dt>Principal claim</dt><dd>${html(claim)}</dd></div></dl>`,
      "  </article>",
    );
  uses.push("</div>", ...figure(3));
  const recursion = [
    ...figure(6),
    '<ul class="recursion-list">',
    ...RECURSION.map(([lead, text]) => `  <li><strong>${html(lead)}</strong> ${html(text)}</li>`),
    "</ul>",
  ];
  const problems = ['<div class="problem-grid">'];
  for (const [direction, serves, question, benchmark] of PROBLEMS)
    problems.push(
      '  <article class="problem-card">',
      `    <h4>${html(direction)}</h4>`,
      `    <p class="problem-tags">${serves.map((name) => `<span>${html(name)}</span>`).join("")}</p>`,
      `    <p class="problem-question">${html(question)}</p>`,
      `    <p class="problem-benchmark"><span>Starting benchmark</span>${html(benchmark)}</p>`,
      "  </article>",
    );
  problems.push(
    "</div>",
    '<h4 class="program-title">Three near-term programs</h4>',
    '<ol class="program-list">',
    ...PROGRAMS.map((program) => `  <li>${html(program)}</li>`),
    "</ol>",
    `<blockquote class="survey-closing">${html(CLOSING)}</blockquote>`,
  );
  const cite = [
    `<pre id="survey-bibtex"><code>${html(surveyBibtex(REPO_URL))}</code></pre>`,
    '<button type="button" class="button button-outline" id="copy-bibtex">Copy BibTeX<img class="icon" src="assets/icons/copy.svg" alt="" width="16" height="16" /></button>',
  ];
  const lines = [
    '<section id="survey" class="survey-section" aria-labelledby="survey-title">',
    '  <div class="container">',
    '    <header class="survey-header" data-reveal>',
    '      <p class="eyebrow section-eyebrow">The survey</p>',
    '      <h2 id="survey-title">What turns physical experience into better learning<span class="heading-dot">?</span></h2>',
    "    </header>",
    ...[
      block(1, "survey-overview", "Overview", "From better behavior to better learning", "knowledge", intro),
      block(2, "survey-questions", "Research questions", "What the survey asks", "shift", questions),
      block(3, "survey-framework", "The review at a glance", "Four uses, four conditions, four claims", "outcome", framework),
      block(4, "survey-uses", "Four uses of acquired change", "Where an acquired change goes next", "retain", uses),
      block(5, "survey-recursion", "Toward recursive self-improvement", "Testing the two links of recursion", "revise", recursion),
      block(6, "survey-problems", "Open problems", "Six directions to start from", "repair", problems),
      block(7, "survey-citation", "Citation", "Cite the survey", "act", cite, " survey-cite"),
    ]
      .flat()
      .map((line) => `    ${line}`),
    "  </div>",
    "</section>",
  ];
  return lines;
}

export function applySurveySection(page) {
  const start = page.indexOf(START);
  const end = page.indexOf(END);
  if (start < 0 || end < start) throw new Error("index.html is missing the survey markers");
  const body = [...renderHero(), ...renderSurveySection()].map((line) => (line ? `      ${line}` : line)).join("\n");
  return `${page.slice(0, start + START.length)}\n${body}\n      ${page.slice(end)}`;
}
if (process.argv[1] && pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url) {
  const file = path.join(ROOT, "index.html");
  const page = await readFile(file, "utf8");
  const output = applySurveySection(page);
  if (process.argv.includes("--check")) {
    if (output !== page) throw new Error("Survey section is out of date. Run npm run readme.");
    console.log("Survey section is synchronized.");
  } else {
    await writeFile(file, output);
    console.log("Survey section rendered into index.html.");
  }
}
