import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { DATA_FILE, REPO_URL, ROOT, SITE_URL } from "./public-files.mjs";
import { venueLabel } from "../site/catalog.js";

const COLORS = {
  conference: "416cb3",
  journal: "087f80",
  preprint: "a04865",
  book: "99700c",
  other: "65716e",
};
const LABELS = {
  conference: "Conference",
  journal: "Journal",
  preprint: "Preprint",
  book: "Book",
  other: "Other",
};

function html(value) {
  return String(value).replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        character
      ],
  );
}

function markdown(value) {
  return String(value)
    .replace(/([\\`*_{}\[\]<>])/g, "\\$1")
    .replace(/\s+/g, " ")
    .trim();
}

function badge(message, color, alt = message) {
  const query = new URLSearchParams({
    label: "",
    message,
    color,
    style: "flat-square",
  });
  return `<img src="https://img.shields.io/static/v1?${html(query.toString())}" alt="${html(alt)}" height="18">`;
}

export function renderReadme(references) {
  const sorted = [...references].sort(
    (a, b) =>
      (b.year ?? 0) - (a.year ?? 0) ||
      a.title.localeCompare(b.title, "en") ||
      a.id.localeCompare(b.id, "en"),
  );
  const years = [...new Set(sorted.map((reference) => reference.year))];
  const lines = [
    "<!-- Generated by tools/render-readme.mjs. Edit the renderer or data/references.json. -->",
    '<div align="center">',
    `  <a href="${SITE_URL}"><img src="assets/readme-banner.png" width="1200" alt="Physical AI Survey"></a>`,
    "",
    "  <h1>Physical AI Survey</h1>",
    "  <p>A public reference library. The survey will follow after publication.</p>",
    "",
    `  <a href="${SITE_URL}">${badge("Project website", "087f80")}</a>`,
    `  <a href="${SITE_URL}#references">${badge(`${references.length} references`, "416cb3")}</a>`,
    `  <a href="#publication">${badge("Survey: forthcoming", "65716e")}</a>`,
    `  <a href="LICENSE">${badge("Code: MIT", "65716e")}</a>`,
    "</div>",
    "",
    `**[Explore the website](${SITE_URL})** | **[Browse references](#references)** | **[Contribute](CONTRIBUTING.md)**`,
    "",
    "## Publication",
    "",
    "This repository is the public home of **Physical AI Survey**. Reference metadata is available now. The manuscript, survey content, and citation will be added after publication.",
    "",
    "| Resource | Availability |",
    "| --- | --- |",
    `| [Project website](${SITE_URL}) | Available |`,
    `| [Reference library](${SITE_URL}#references) | Available |`,
    "| Survey and citation | Forthcoming |",
    "",
    "## References",
    "",
    `${references.length} public bibliographic records, ordered from newest to oldest. Publication badges describe the venue or record type.`,
    "",
    Object.entries(LABELS)
      .map(([type, label]) => badge(label, COLORS[type]))
      .join(" "),
    "",
    years
      .map(
        (year) =>
          `[${year ?? "Year unavailable"}](#${year ?? "year-unavailable"})`,
      )
      .join(" | "),
    "",
  ];
  for (const year of years) {
    lines.push(`### ${year ?? "Year unavailable"}`, "");
    for (const reference of sorted.filter((item) => item.year === year)) {
      const link = reference.url ? ` [[paper](<${reference.url}>)]` : "";
      const title = markdown(reference.title);
      lines.push(
        `- ${title}${/[.!?]$/.test(title) ? "" : "."}${link} ${badge(venueLabel(reference), COLORS[reference.type], reference.venue || LABELS[reference.type])}`,
      );
    }
    lines.push("");
  }
  lines.push(
    "## Repository guide",
    "",
    "| Path | Purpose |",
    "| --- | --- |",
    "| [`data/references.json`](data/references.json) | Shared public bibliographic metadata |",
    "| [`site/`](site/) | Website styles and browser code |",
    "| [`assets/`](assets/) | Public artwork and asset credits |",
    "| [`tools/`](tools/) | README generation, validation, build, and preview |",
    "| [Maintenance](docs/MAINTENANCE.md) | Update and validation workflow |",
    "| [Deployment](docs/DEPLOYMENT.md) | GitHub Pages configuration |",
    "",
    "## Contributing",
    "",
    `Found incorrect metadata or a broken link? [Open an issue](${REPO_URL}/issues/new/choose) or follow [CONTRIBUTING.md](CONTRIBUTING.md). Contributions currently cover public reference metadata and the project website.`,
    "",
    "## License",
    "",
    "The original website code and technical documentation are available under the [MIT License](LICENSE). Linked publications, third-party assets, and publication text retain their respective rights and licenses. See [asset credits](assets/CREDITS.md).",
    "",
  );
  return lines.join("\n");
}

if (
  process.argv[1] &&
  pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url
) {
  const references = JSON.parse(
    await readFile(path.join(ROOT, DATA_FILE), "utf8"),
  );
  const output = renderReadme(references);
  if (process.argv.includes("--check")) {
    const current = await readFile(path.join(ROOT, "README.md"), "utf8");
    if (current !== output)
      throw new Error("README is out of date. Run npm run readme.");
    console.log(`README is synchronized with ${references.length} references.`);
  } else {
    await writeFile(path.join(ROOT, "README.md"), output);
    console.log(
      `README generated from ${references.length} public references.`,
    );
  }
}
