import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import {
  DATA_FILE,
  PROJECT_NAME,
  REPO_URL,
  ROOT,
  SITE_URL,
} from "./public-files.mjs";
import { venueLabel } from "../site/catalog.js";

const COLORS = {
  conference: "416cb3",
  journal: "087f80",
  preprint: "a04865",
  book: "99700c",
  other: "65716e",
};
const LABELS = {
  conference: "Conference",
  journal: "Journal",
  preprint: "Preprint",
  book: "Book",
  other: "Other",
};

function html(value) {
  return String(value).replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        character
      ],
  );
}

function markdown(value) {
  return String(value)
    .replace(/([\\`*_{}\[\]<>])/g, "\\$1")
    .replace(/\s+/g, " ")
    .trim();
}

function badge(message, color, alt = message) {
  const query = new URLSearchParams({
    label: "",
    message,
    color,
    style: "flat-square",
  });
  return `<img src="https://img.shields.io/static/v1?${html(query.toString())}" alt="${html(alt)}" height="18">`;
}

export function renderReadme(references) {
  const sorted = [...references].sort(
    (a, b) =>
      (b.year ?? 0) - (a.year ?? 0) ||
      a.title.localeCompare(b.title, "en") ||
      a.id.localeCompare(b.id, "en"),
  );
  const years = [...new Set(sorted.map((reference) => reference.year))];
  const counts = Object.fromEntries(
    Object.keys(LABELS).map((type) => [
      type,
      references.filter((reference) => reference.type === type).length,
    ]),
  );
  const lines = [
    "<!-- Generated by tools/render-readme.mjs. Edit the renderer or data/references.json. -->",
    '<div align="center">',
    `  <a href="${SITE_URL}"><img src="assets/readme-banner.png" width="1200" alt="${html(PROJECT_NAME)}"></a>`,
    "",
    "  <p><strong>A Survey and Reference Library</strong></p>",
    "",
    `  <a href="${SITE_URL}">${badge("Project website", "087f80")}</a>`,
    `  <a href="${SITE_URL}#references">${badge(`${references.length} references`, "416cb3")}</a>`,
    `  <a href="LICENSE">${badge("Code: MIT", "65716e")}</a>`,
    "</div>",
    "",
    `**[Website](${SITE_URL})** | **[References](#references)** | **[Repository guide](#repository-guide)** | **[Contribute](CONTRIBUTING.md)**`,
    "",
    '<a id="publication"></a>',
    "",
    "**Publication status:** Reference metadata is public. The survey content and citation will follow after publication.",
    "",
    "The project covers Physical AI and recursive self-improvement (RSI). The collection includes related and foundational work; inclusion does not imply that a paper demonstrates RSI.",
    "",
    "## Repository guide",
    "",
    "| Path | Purpose |",
    "| --- | --- |",
    "| [`data/references.json`](data/references.json) | Shared public bibliographic metadata |",
    "| [`site/`](site/) | Website styles and browser code |",
    "| [`assets/`](assets/) | Public artwork and asset credits |",
    "| [`tools/`](tools/) | README generation, validation, build, and preview |",
    "",
    "[Bibliography updates](data/README.md) | [Maintenance](docs/MAINTENANCE.md) | [Deployment](docs/DEPLOYMENT.md) | [Publication checklist](docs/PUBLICATION.md) | [Asset credits](assets/CREDITS.md)",
    "",
    "## References",
    "",
    `${references.length} public bibliographic records, ordered from newest to oldest. Counts describe this collection; publication badges indicate the venue or record type.`,
    "",
    `| ${Object.values(LABELS).join(" | ")} |`,
    `| ${Object.keys(LABELS)
      .map(() => "---:")
      .join(" | ")} |`,
    `| ${Object.keys(LABELS)
      .map((type) => counts[type])
      .join(" | ")} |`,
    "",
    Object.entries(LABELS)
      .map(([type, label]) => badge(label, COLORS[type]))
      .join(" "),
    "",
    years
      .map(
        (year) =>
          `[${year ?? "Year unavailable"}](#year-${year ?? "unavailable"})`,
      )
      .join(" | "),
    "",
  ];
  for (const year of years) {
    const records = sorted.filter((item) => item.year === year);
    const collapsed = year !== years[0];
    lines.push(`<a id="year-${year ?? "unavailable"}"></a>`, "");
    if (collapsed) {
      lines.push(
        "<details>",
        `<summary><strong>${year ?? "Year unavailable"}</strong> &middot; ${records.length} references</summary>`,
        "",
      );
    } else lines.push(`### ${year ?? "Year unavailable"}`, "");
    for (const reference of records) {
      const link = reference.url ? ` [[paper](<${reference.url}>)]` : "";
      const title = markdown(reference.title);
      lines.push(
        `- ${title}${/[.!?]$/.test(title) ? "" : "."}${link} ${badge(venueLabel(reference), COLORS[reference.type], reference.venue || LABELS[reference.type])}`,
      );
    }
    lines.push("");
    if (collapsed) lines.push("</details>", "");
  }
  lines.push(
    "## Contributing",
    "",
    `Found incorrect metadata or a broken link? [Open an issue](${REPO_URL}/issues/new/choose) or follow [CONTRIBUTING.md](CONTRIBUTING.md). Contributions currently cover public reference metadata and the project website.`,
    "",
    "## License",
    "",
    "The original website code and technical documentation are available under the [MIT License](LICENSE). Linked publications, third-party assets, and publication text retain their respective rights and licenses. See [asset credits](assets/CREDITS.md).",
    "",
  );
  return lines.join("\n");
}

if (
  process.argv[1] &&
  pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url
) {
  const references = JSON.parse(
    await readFile(path.join(ROOT, DATA_FILE), "utf8"),
  );
  const output = renderReadme(references);
  if (process.argv.includes("--check")) {
    const current = await readFile(path.join(ROOT, "README.md"), "utf8");
    if (current !== output)
      throw new Error("README is out of date. Run npm run readme.");
    console.log(`README is synchronized with ${references.length} references.`);
  } else {
    await writeFile(path.join(ROOT, "README.md"), output);
    console.log(
      `README generated from ${references.length} public references.`,
    );
  }
}
