import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import {
  DATA_FILE,
  PROJECT_NAME,
  REPO_URL,
  ROOT,
  SITE_URL,
} from "./public-files.mjs";
import { venueLabel } from "../site/catalog.js";
import {
  ABOUT,
  CLOSING,
  CONDITIONS,
  CONDITIONS_NOTE,
  EVIDENCE,
  FIGURES,
  OUTLINE,
  PROBLEMS,
  PROGRAMS,
  QUESTIONS,
  RECURSION,
  SURVEY,
  TEASER_ALT,
  USES,
  surveyBibtex,
} from "./survey-content.mjs";

const COLORS = {
  conference: "416cb3",
  journal: "087f80",
  preprint: "a04865",
  book: "99700c",
  other: "65716e",
};
const LABELS = {
  conference: "Conference",
  journal: "Journal",
  preprint: "Preprint",
  book: "Book",
  other: "Other",
};
// Section icons (assets/readme/icons, drawn by tools/draw-readme-art.mjs)
const ICON = {
  "About the survey": "about",
  "Research questions": "questions",
  "Repository guide": "guide",
  "The review at a glance": "framework",
  "Four uses of acquired change": "uses",
  "Toward recursive self-improvement": "recursion",
  "Open problems": "problems",
  References: "references",
  Contributing: "contribute",
  Contributors: "contributors",
  "Star history": "star",
  Citation: "cite",
  "Repository layout": "layout",
  License: "license",
};
// Section cards (assets/readme/card-*.svg): [file key, section linked to, alt text]
const CARDS = [
  ["about", "About the survey", "Overview: from experience to recursion"],
  ["questions", "Research questions", "Research questions: what limits the next gain?"],
  ["framework", "The review at a glance", "The review at a glance: uses, conditions, claims"],
  ["recursion", "Toward recursive self-improvement", "Toward RSI: testing the two links"],
  ["problems", "Open problems", "Open problems: six directions to start"],
  ["references", "References", "References: the survey's library"],
];
const CONDITION_ORDER = CONDITIONS.map(([name]) => name);

function html(value) {
  return String(value).replace(
    /[&<>"']/g,
    (character) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        character
      ],
  );
}

function markdown(value) {
  return String(value)
    .replace(/([\\`*_{}\[\]<>])/g, "\\$1")
    .replace(/\s+/g, " ")
    .trim();
}

function badge(message, color, alt = message) {
  const query = new URLSearchParams({
    label: "",
    message,
    color,
    style: "flat-square",
  });
  return `<img src="https://img.shields.io/static/v1?${html(query.toString())}" alt="${html(alt)}" height="18">`;
}

// An image that follows the reader's GitHub theme: `${stem}-dark.svg` / `${stem}-light.svg`, on one line.
function themed(stem, attributes) {
  return (
    `<picture><source media="(prefers-color-scheme: dark)" srcset="${stem}-dark.svg">` +
    `<source media="(prefers-color-scheme: light)" srcset="${stem}-light.svg"><img src="${stem}-light.svg" ${attributes}></picture>`
  );
}

// GitHub's heading anchor for the plain-text headings used here
function anchor(heading) {
  return heading
    .toLowerCase()
    .replace(/[^a-z0-9 -]/g, "")
    .replaceAll(" ", "-");
}

function figure(number) {
  const [title, caption] = FIGURES[number];
  return [
    `<p align="center"><img src="assets/readme/figures/figure-${number}.png" width="900" alt="Figure ${number}. ${html(title)} ${html(caption)}"></p>`,
    `<p align="center"><sub><b>Figure ${number}. ${html(title)}</b> ${html(caption)}</sub></p>`,
    "",
  ];
}

export function renderReadme(references) {
  const sorted = [...references].sort(
    (a, b) =>
      (b.year ?? 0) - (a.year ?? 0) ||
      a.title.localeCompare(b.title, "en") ||
      a.id.localeCompare(b.id, "en"),
  );
  const years = [...new Set(sorted.map((reference) => reference.year))];
  const counts = Object.fromEntries(
    Object.keys(LABELS).map((type) => [
      type,
      references.filter((reference) => reference.type === type).length,
    ]),
  );
  const slug = REPO_URL.replace("https://github.com/", "");
  const lines = [];
  const add = (...items) => lines.push(...items);
  let backLinks = false; // once the main sections start, each one is preceded by a link back to the guide
  const heading = (title) => {
    if (backLinks)
      add('<p align="right"><sub><a href="#repository-guide">↑ Back to guide</a></sub></p>', "");
    add(themed(`assets/readme/icons/${ICON[title]}`, 'alt="" width="36" align="left"'), "", `## ${title}`, "");
  };

  add(
    "<!-- Generated by tools/render-readme.mjs. Edit the renderer, tools/survey-content.mjs or data/references.json. -->",
    '<div align="center">',
    `  <a href="${SITE_URL}"><img src="assets/readme-banner.png" width="1200" alt="${html(`${PROJECT_NAME}: ${SURVEY.title}. ${SURVEY.subtitle}. ${TEASER_ALT}`)}"></a>`,
    "",
    "  <p><strong><em>⭐ Star us if you find this useful!</em></strong></p>",
    "",
    `  <a href="${SITE_URL}">${badge("Project website", "087f80")}</a>`,
    `  <a href="#publication">${badge("Paper: coming soon", "914252")}</a>`,
    `  <a href="${SITE_URL}#references">${badge(`${references.length} references`, "416cb3")}</a>`,
    `  <a href="LICENSE">${badge("Code: MIT", "65716e")}</a>`,
    '  <a href="https://awesome.re"><img src="https://awesome.re/badge-flat2.svg" alt="Awesome" height="18"></a>',
    "",
    "  <p>" +
      SURVEY.authors
        .map(([name, affiliations, url]) => {
          const label = url ? `<a href="${url}">${html(name)}</a>` : html(name);
          return `${label}<sup>${affiliations.join(",")}</sup>`;
        })
        .join(" · ") +
      "</p>",
    `  <p><sub>${SURVEY.affiliations.map((name, i) => `<sup>${i + 1}</sup> ${html(name)}`).join(" &nbsp;·&nbsp; ")}</sub></p>`,
    "</div>",
    "",
    '<a id="publication"></a>',
    "",
    "> [!NOTE]",
    "> The manuscript is not yet public. This page summarizes it with the authors' approval; a link to the paper will follow its release.",
    "",
  );

  heading("About the survey");
  for (const paragraph of ABOUT) add(paragraph, "");
  add("> [!IMPORTANT]", "> **Four recurring conditions shape further improvement.**", ">");
  for (const [name, text] of CONDITIONS) add(`> - **${name}:** ${text}`);
  add(">", `> ${CONDITIONS_NOTE}`, "");
  add(...figure(1));

  heading("Research questions");
  add("| | Question | What it asks |", "| :-: | --- | --- |");
  for (const [id, question, detail] of QUESTIONS) add(`| **${id}** | **${question}** | ${detail} |`);
  add("");

  const sections = [
    "About the survey",
    "Research questions",
    "The review at a glance",
    "Four uses of acquired change",
    "Toward recursive self-improvement",
    "Open problems",
    "References",
    "Contributing",
    "Contributors",
    "Star history",
    "Citation",
    "Repository layout",
    "License",
  ];
  heading("Repository guide");
  add(
    sections.map((title) => `[${title}](#${anchor(title)})`).join(" · "),
    "",
    "## Choose a section",
    "",
    "Select a card to jump directly to its section.",
    "",
    '<p align="center">',
  );
  for (const [i, [key, title, alt]] of CARDS.entries()) {
    if (i === 3) add("  <br>");
    add(`  <a href="#${anchor(title)}">${themed(`assets/readme/card-${key}`, `width="246" alt="${html(alt)}"`)}</a>`);
  }
  add("</p>", "", "---", "");

  heading("The review at a glance");
  backLinks = true;
  add(...figure(2));
  add("> [!NOTE]", `> **What current evidence shows.** ${EVIDENCE}`, "");
  add("<details>", "<summary><b>Survey outline</b></summary>", "", "| § | Chapter | Covers |", "| :-: | --- | --- |");
  for (const [number, chapter, covers] of OUTLINE) add(`| ${number} | **${chapter}** | ${covers} |`);
  add("", "</details>", "");

  heading("Four uses of acquired change");
  add(
    "The same physical experience can leave very different kinds of change behind, and each has a different next user. Each system is placed by the use that its main experiment tests.",
    "",
    "| Use | Retained change | Immediate use | Principal claim | Chapter |",
    "| --- | --- | --- | --- | --- |",
  );
  for (const [use, change, next, claim, chapter] of USES) add(`| **${use}** | ${change} | ${next} | ${claim} | ${chapter} |`);
  add("");
  add(...figure(3));

  heading("Toward recursive self-improvement");
  add(...figure(6));
  for (const [lead, text] of RECURSION) add(`- **${lead}** ${text}`);
  add("");

  heading("Open problems");
  add(
    "Six directions, the condition each mainly serves, its central question, and a benchmark from which a new project could start.",
    "",
    "| Direction | Serves | Central question | Starting benchmark |",
    "| --- | --- | --- | --- |",
  );
  for (const [direction, serves, question, benchmark] of PROBLEMS) {
    const marks = [...serves].sort((x, y) => CONDITION_ORDER.indexOf(x) - CONDITION_ORDER.indexOf(y)).join("<br>");
    add(`| **${direction}** | ${marks} | ${question} | ${benchmark} |`);
  }
  add("", "**Three near-term programs follow from this agenda:**", "");
  PROGRAMS.forEach((program, i) => add(`${i + 1}. ${program}`));
  add("", `> *${CLOSING}*`, "");

  heading("References");
  add(
    `${references.length} bibliographic records from the survey, ordered from newest to oldest. Counts describe this collection; publication badges indicate the venue or record type. Inclusion does not imply that a paper demonstrates RSI. The [project website](${SITE_URL}#references) adds search and filters.`,
    "",
    `| ${Object.values(LABELS).join(" | ")} |`,
    `| ${Object.keys(LABELS)
      .map(() => "---:")
      .join(" | ")} |`,
    `| ${Object.keys(LABELS)
      .map((type) => counts[type])
      .join(" | ")} |`,
    "",
    Object.entries(LABELS)
      .map(([type, label]) => badge(label, COLORS[type]))
      .join(" "),
    "",
    years
      .map(
        (year) =>
          `[${year ?? "Year unavailable"}](#year-${year ?? "unavailable"})`,
      )
      .join(" | "),
    "",
  );
  for (const year of years) {
    const records = sorted.filter((item) => item.year === year);
    const collapsed = year !== years[0];
    lines.push(`<a id="year-${year ?? "unavailable"}"></a>`, "");
    if (collapsed) {
      lines.push(
        "<details>",
        `<summary><strong>${year ?? "Year unavailable"}</strong> &middot; ${records.length} references</summary>`,
        "",
      );
    } else lines.push(`### ${year ?? "Year unavailable"}`, "");
    for (const reference of records) {
      const link = reference.url ? ` [[paper](<${reference.url}>)]` : "";
      const title = markdown(reference.title);
      lines.push(
        `- ${title}${/[.!?]$/.test(title) ? "" : "."}${link} ${badge(venueLabel(reference), COLORS[reference.type], reference.venue || LABELS[reference.type])}`,
      );
    }
    lines.push("");
    if (collapsed) lines.push("</details>", "");
  }

  heading("Contributing");
  add(
    `Found incorrect metadata or a broken link? [Open an issue](${REPO_URL}/issues/new/choose) or follow [CONTRIBUTING.md](CONTRIBUTING.md). Contributions currently cover public reference metadata and the project website.`,
    "",
  );
  heading("Contributors");
  add(
    "Thanks to everyone who has corrected references and improved the project.",
    "",
    `<a href="${REPO_URL}/graphs/contributors"><img src="https://contrib.rocks/image?repo=${slug}" alt="Contributors to ${slug}"></a>`,
    "",
  );
  heading("Star history");
  const chart = `https://api.star-history.com/svg?repos=${slug}&type=Date`;
  add(
    '<p align="center">',
    `  <a href="https://star-history.com/#${slug}&Date">`,
    "    <picture>",
    `      <source media="(prefers-color-scheme: dark)" srcset="${chart}&theme=dark">`,
    `      <source media="(prefers-color-scheme: light)" srcset="${chart}">`,
    `      <img alt="Star history of ${slug}" src="${chart}" width="800">`,
    "    </picture>",
    "  </a>",
    "</p>",
    "",
  );
  heading("Citation");
  add(
    "If you find the survey or the reference library useful, please cite:",
    "",
    "```bibtex",
    surveyBibtex(REPO_URL),
    "```",
    "",
  );
  heading("Repository layout");
  add(
    "| Path | Purpose |",
    "| --- | --- |",
    "| [`data/references.json`](data/references.json) | Shared public bibliographic metadata |",
    "| [`site/`](site/) | Website styles and browser code |",
    "| [`assets/`](assets/) | Public artwork, README figures and asset credits |",
    "| [`tools/`](tools/) | README generation and artwork, validation, build, and preview |",
    "",
    "[Bibliography updates](data/README.md) | [Maintenance](docs/MAINTENANCE.md) | [Deployment](docs/DEPLOYMENT.md) | [Publication checklist](docs/PUBLICATION.md) | [Asset credits](assets/CREDITS.md)",
    "",
  );
  heading("License");
  add(
    "The original website code and technical documentation are available under the [MIT License](LICENSE). The survey figures and summary text are © the authors and appear here with their approval; they are not covered by the code license. Linked publications, third-party assets, and publication text retain their respective rights and licenses. See [asset credits](assets/CREDITS.md).",
    "",
  );
  return lines.join("\n");
}

if (
  process.argv[1] &&
  pathToFileURL(path.resolve(process.argv[1])).href === import.meta.url
) {
  const references = JSON.parse(
    await readFile(path.join(ROOT, DATA_FILE), "utf8"),
  );
  const output = renderReadme(references);
  if (process.argv.includes("--check")) {
    const current = await readFile(path.join(ROOT, "README.md"), "utf8");
    if (current !== output)
      throw new Error("README is out of date. Run npm run readme.");
    console.log(`README is synchronized with ${references.length} references.`);
  } else {
    await writeFile(path.join(ROOT, "README.md"), output);
    console.log(
      `README generated from ${references.length} public references.`,
    );
  }
}
